# Generated by Django 5.0.6 on 2024-07-04 11:15

from django.db import migrations
import random

def create_stock_data(apps, schema_editor):
    Stock = apps.get_model('stock', 'Stock')
    stock_data = [
        Stock(
            name=f'Producto {i}',
            quantity=random.randint(1, 100),
            price=round(random.uniform(1, 100), 2)
        ) for i in range(1, 51)
    ]
    Stock.objects.bulk_create(stock_data)

def reverse_stock_data(apps, schema_editor):
    Stock = apps.get_model('stock', 'Stock')
    Stock.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_stock_data, reverse_stock_data),
    ]
